server:
  port: 8080

spring:
  application:
    name: cake-order-platform

  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:CAKE_ORDER_PLATFORM_DB;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/ddl.sql

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # sql 파라미터 확인을 위함

jwt:
  issuer: cake-order-platform-server
  secret_key: ZmFrZS1zZWNyZXQta2V5LWZvci1kZW1vLXVzZS0xMjM0NTY3ODkwMTIz # 최소 32바이트 이상, Base64 인코딩값을 추천한다.

crypto:
  encrypt:
    password: test-password
    salt: 5c0744940b5c369b

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}

payment:
  success-url: ${PAYMENT_SUCCESS_URL}
  fail-url: ${PAYMENT_FAIL_URL}